### ISSUE TITLE
Update for Cake 2.x

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.Recipe#256]
Update all addins to Cake 2.0 and require Cake 2.0 or newer for Frosting recipe

- [x] Cake.AzureDevOps
- [x] Cake.Git
- [x] Cake.Issues (https://github.com/cake-contrib/Cake.Issues/issues/263)
- [x] Cake.Issues.MsBuild (https://github.com/cake-contrib/Cake.Issues.MsBuild/issues/257)
- [x] Cake.Issues.InspectCode (https://github.com/cake-contrib/Cake.Issues.InspectCode/issues/188)
- [x] Cake.Issues.DupFinder (https://github.com/cake-contrib/Cake.Issues.DupFinder/issues/95)
- [x] Cake.Issues.Markdownlint (https://github.com/cake-contrib/Cake.Issues.Markdownlint/issues/175)
- [x] Cake.Issues.EsLint (https://github.com/cake-contrib/Cake.Issues.EsLint/issues/175)
- [x] Cake.Issues.Reporting (https://github.com/cake-contrib/Cake.Issues/issues/263)
- [x] Cake.Issues.Reporting.Generic (https://github.com/cake-contrib/Cake.Issues.Reporting.Generic/issues/425)
- [x] Cake.Issues.PullRequests (https://github.com/cake-contrib/Cake.Issues/issues/263)
- [x] Cake.Issues.PullRequests.AppVeyor (https://github.com/cake-contrib/Cake.Issues.PullRequests.AppVeyor/issues/151)
- [x] Cake.Issues.PullRequests.AzureDevOps (https://github.com/cake-contrib/Cake.Issues.PullRequests.AzureDevOps/issues/250)
- [x] Cake.Issues.PullRequests.GitHubActions (https://github.com/cake-contrib/Cake.Issues.PullRequests.GitHubActions/issues/124)
