### ISSUE TITLE
Update for Cake 4.x

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.Recipe#390]
Update all addins to Cake 4.0 and require Cake 4.0 or newer for Frosting recipe

- [x] Cake.AzureDevOps (https://github.com/cake-contrib/Cake.AzureDevOps/issues/450)
- [ ] Cake.Git ()
- [x] Cake.Issues (https://github.com/cake-contrib/Cake.Issues/issues/381)
- [x] Cake.Issues.MsBuild (https://github.com/cake-contrib/Cake.Issues.MsBuild/issues/358)
- [x] Cake.Issues.InspectCode (https://github.com/cake-contrib/Cake.Issues.InspectCode/issues/260)
- [ ] Cake.Issues.Markdownlint (https://github.com/cake-contrib/Cake.Issues.Markdownlint/issues/247)
- [x] Cake.Issues.EsLint (https://github.com/cake-contrib/Cake.Issues.EsLint/issues/250)
- [x] Cake.Issues.Reporting (https://github.com/cake-contrib/Cake.Issues/issues/381)
- [x] Cake.Issues.Reporting.Generic (https://github.com/cake-contrib/Cake.Issues.Reporting.Generic/issues/548)
- [ ] Cake.Issues.Reporting.Sarif (https://github.com/cake-contrib/Cake.Issues.Reporting.Sarif/issues/214)
- [x] Cake.Issues.PullRequests (https://github.com/cake-contrib/Cake.Issues/issues/381)
- [x] Cake.Issues.PullRequests.AppVeyor (https://github.com/cake-contrib/Cake.Issues.PullRequests.AppVeyor/issues/218)
- [x] Cake.Issues.PullRequests.AzureDevOps (https://github.com/cake-contrib/Cake.Issues.PullRequests.AzureDevOps/issues/349)
- [x] Cake.Issues.PullRequests.GitHubActions (https://github.com/cake-contrib/Cake.Issues.PullRequests.GitHubActions/issues/200)
